//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    [Bind(Exclude = "iId")]
    public partial class t_UserReg
    {
        [ScaffoldColumn(false)]
        public int iId { get; set; }
        [Required(ErrorMessage ="Enter User Id")]
       [StringLength(12,ErrorMessage ="UserId must be in beteween 4 to 10 character",MinimumLength =4)]
        public string sUserId { get; set; }
        [Required(ErrorMessage ="Enter Password")]
        [DataType(DataType.Password)]
        [StringLength(12, ErrorMessage = "Pasword Minimum 6 character and maximum 12", MinimumLength = 6)]
        public string sPassword { get; set; }

        [Required(ErrorMessage = "Enter Email")]
        [DataType(DataType.EmailAddress)]
        public string sEmail { get; set; }
       
        [Required(ErrorMessage ="Enter Phone Number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$")]
        public string iPhoneNumber { get; set; }
    }
    public class Login
    {
        [Required(ErrorMessage ="Please Enter User Name")]
        [StringLength(1024,ErrorMessage ="Name Max Limit Exceed!!!")]
        [Display(Name ="UserName")]
        public string sUserId { get; set; }

        [Required(ErrorMessage ="Please Enter Password")]
        [Display(Name ="Password")]
        [StringLength(12,ErrorMessage ="Pasword Minimum 6 character and maximum 12",MinimumLength =6)]
       
        public string sPassword { get; set; }

       
    }
}
