//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_UserReg
    {
        public int iId { get; set; }
        public string sUserId { get; set; }
        public string sPassword { get; set; }
        public string sEmail { get; set; }
        public string iPhoneNumber { get; set; }
    }
}
